version: '3.8'

services:
  openhab:
    image: localhost:32777/openhab
    container_name: openhab
    restart: always
    ports:
      - "31775:8080"
      - "31443:8443"
    volumes:
      - "./openhab/addons:/openhab/addons"
      - "./openhab/conf:/openhab/conf"
      - "./openhab/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Moscow"
      LC_ALL: ru_RU.UTF-8
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
      # USER_ID: 1001
      # GROUP_ID: 9001
